### ISSUE TITLE
Assets Published unclear

### ISSUE THREAD

**Issue by stefanstranger** [JakobGSvendsen/AzureAutomationImportExport#2]
Hi Jakob,

What is the following code exactly doing? Line 204 .. 213. I don't see any AssetsDraft variable set.

 $AssetsPublished = Get-RunbookAssets -RunbookContent $ContentDraft -ResourceGroupName $ResourceGroupName -AutomationAccountName $AutomationAccountName
    if(![String]::IsNullOrEmpty($AssetsPublished)) {    
        $XMLExportFile.Runbook.Draft.Assets = [String]($AssetsDraft  | select-object Type, Name, Encrypted, Value, Description | ConvertTo-Json)
    }

    $AssetsPublished = Get-RunbookAssets -RunbookContent $ContentPublished -ResourceGroupName $ResourceGroupName -AutomationAccountName $AutomationAccountName
    if(![String]::IsNullOrEmpty($AssetsPublished)) {
        $XMLExportFile.Runbook.Published.Assets = [String]($AssetsDraft | select-object Type, Name, Encrypted, Value, Description  | ConvertTo-Json)
    }

**Comment by JakobGSvendsen** [comment]
Woops was a typo when trying to fix an issue, which made it worse! LOL

Now it is fixed.

it is supposed to get get runbook assets and insert in XML.
